# Generated by Django 3.2.9 on 2021-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
