# Generated by Django 3.2.9 on 2021-11-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20211115_0956'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
    ]
